### ISSUE TITLE
CPU bound at high download speeds – need resource management

### ISSUE THREAD

**Issue by dcposch** [webtorrent/webtorrent#1026]
**What version of WebTorrent?**
WebTorrent Desktop 0.17.2

**What operating system and hardware?**
MacOS Sierra

2016 12" Macbook, plugged in

**What did you expect to happen?**
Download speed limited only by available network bandwidth and peers.

**What actually happened?**
It looks like WebTorrent is saturating the CPU during fast downloads:

![image](https://cloud.githubusercontent.com/assets/169280/22277251/f96b1d62-e26e-11e6-802d-13d23065b344.png)

**Comment by dcposch** [comment]
@feross two ideas:
1. We could use the node profiler to figure out where WebTorrent is spending time in JS
2. If it turns out as I suspect and a lot of time is spent in Chromium because of WebRTC, then we could try setting a global limit on the number of peers we talk to at once. We'd prioritize the fastest peers.

**Comment by DiegoRBaquero** [comment]
My guess is that the hashing to verify the pieces is the CPU-consuming monster.

**Comment by feross** [comment]
@dcposch We ought to do both IMO

**Comment by sliterok** [comment]
Also ram consumption is really heavy
![image](https://cloud.githubusercontent.com/assets/12751644/22626962/5242b20a-ebda-11e6-9f39-b9ed4a545383.png)
![image](https://cloud.githubusercontent.com/assets/12751644/22626964/5de3defe-ebda-11e6-961f-e05dfdc13e23.png)

**Comment by catchstar** [comment]
@sliterok 
i have the same issue. Webtorrent can't release the memory even i have removed the torrent by client.remove(). When i add some more magnet it occurs an memory leak error.
Do you have solve the problem? please tell me. 
the same issue: https://github.com/webtorrent/webtorrent/issues/1104

**Comment by sliterok** [comment]
@catchstar 
Hm, i've experienced memory leaks only when i download something.
BTW I haven't solved this trouble, but now i'm using qbittorrent.

**Comment by catchstar** [comment]
@sliterok
i see. Thank you.

**Comment by crzidea** [comment]
I have the same issue. Can't release memory after remove torrent.

**Comment by crzidea** [comment]
Solved, this issue is caused by `dht` options. Tune the option to reduce resource usage.

**Comment by catchstar** [comment]
@crzidea 
i don't think this is a good solution because when use webtorrent to download  by magnet it will fail because of tune the dht option to false. 
i still can't solve this issue.

**Comment by crzidea** [comment]
@catchstar No need to set the option to false, just tune the numbers for `torrent-dht`.

**Comment by catchstar** [comment]
@crzidea
Thanks a lot. it works.

**Comment by CyberShadow** [comment]
[Here is a trace I did back in April for webtorrent-cli](https://github.com/webtorrent/webtorrent/files/1050627/output.txt). The process becomes so CPU-bound, that the player can't even request more chunks quickly enough for continuous playback, despite webtorrent-cli having already downloaded a big % of the file.

Looking at the trace, it looks like `validateWire` is the likely culprit. It seems to be called from a lot of places and seems to do a lot of work.

**Comment by vankasteelj** [comment]
subscribing (from #1224 )


What's your DHT tuned option? I'm only using this so far: 

```
Streamer.client = new (require('webtorrent'))({
                maxConns: 40,
                tracker: {
                    wrtc: false
                }
});
```

**Comment by feross** [comment]
This issue is improved by https://github.com/webtorrent/bittorrent-protocol/pull/52 which seems to fix an issue where 25% of the CPU time was spent repeatedly calling `clearTimeout` and `setTimeout`.

**Comment by martinsangdo** [comment]
Hi @feross 
I pulled "bittorrent-protocol", "version": "3.3.1". Is it included this fix?

**Comment by vankasteelj** [comment]
I seem to have fixed this with webtorrent 1.8.22, limit MaxConns to 40 and force-disable WebSeeds. I'm using NWjs for the app and with WebSeeds enabled it made the application "hang" and stop working. It doesn't seem to impact the download or upload speed of torrents, but I'm unsure of what exactly are webseeds so it might impact you more than me

**Comment by vankasteelj** [comment]
**What version of this package are you using?**
1.8.22

**What operating system, Node.js, and npm version?**
OS: Win11 x64 // Node 18.3 / npm 8.10
The package is used through NWjs 0.65.1 (chromium 102+)

**What happened?**
Connecting to a highly-shared torrent through webtorrent makes NWjs freeze and stop working (thus: no logs, but there are no errors reported prior to the freeze). The Windows taks manager reports NWjs using progressively more RAM and CPU, like it's stuck in a loop. Usage is usually 5 to 30% CPU (on a laptop i5), RAM 1 to 3 Gigs. Upon freeze, it goes up step by step towards 40-50-60-70-80% cpu usage and 5 to 8 Gigs of memory usage. 

This happens a few seconds after webtorrent is fired and fed a torrent, after it connects to peers and starts downloading. In most of my observations, it has time to download 1Mb to 20Mb of the requested file before it fails.

This only happens when using webtorrent inside the NWjs app, never when using it for something else than downloading a torrent, so it's not "just" NWjs freezing (but it might be a combination of nwjs+webtorrent, I'm not excluding it). 

It also does not seem to be a problem on large desktop CPUs : using an hexacore Ryzen 3600 (65W) never freezes, yet using a low-powered i5 (15W) from my laptop (Microsoft Surface Pro) does make it freeze almost every time. The other difference between the machines is the available total memory (32gigs vs 8gigs), but I doubt it's that because as I said it only uses a few gigs max when it doesn't start to hang and freeze. 

My best guess is that it's doing "too many things" at once. It does similar things with badly-written loops that make heavy calculations every time it loops, for example. It eventually "floods" the internal memory (of node? of nwjs? Idk). Maybe it is connecting to too many peers at once, making the javascript engine hang. But lowering the MaxConns option doesn't prevent the freeze anyway, so it might not be that. Limiting download/upload speed does not prevent this either.

I've seen things that COULD be related but I haven't seen my exact problem yet: 
- https://github.com/webtorrent/webtorrent/issues/1026
- https://github.com/webtorrent/webtorrent/issues/1224

**What did you expect to happen?**
Things to work as they did with 0.108.6, back with that version it never had any issues (I reverted to using it, but that's old code by now, fixes and features were added since then). 

**Are you willing to submit a pull request to fix this bug?**
I wouldn't know how to fix the issue, otherwise I would have solved it and proposed the fix here :)

**Comment by vankasteelj** [comment]
FYI, using webtorrent 1.9.7 I do not seem to have the issue anymore. Can anyone else confirm?

**Comment by ThaUnknown** [comment]
I can reach speeds of 60MB/s before maxxing out my CPU, is this not enough?
![image](https://github.com/webtorrent/webtorrent/assets/6506529/2338cc1f-aa87-4a01-bb41-83bc0978e265)
looking at the profiler, most of this is gonna come from native IO rather than JS itself, so there's not much to improve here anymore
