### ISSUE TITLE
Is the Web to Ephemeral?

### ISSUE THREAD

**Issue by cphoover** [webtorrent/webtorrent#1084]
I thought one of the reason bittorrent worked was because it seeds even when you are not at your computer... or using the application. Isn't the nature of web browsing too ephemeral for such a model to work?  We are only seeding when we are on a particular website... I see something like this being super useful for static assets/scripts that are shared across many websites... But how well does this work with unique impermanent things on the web. Just an issue for discussion.

**Comment by kocoten1992** [comment]
I see this as a way to reduce server load, as peak hour when many user want that content, the server will have to do very least work.

**Comment by feross** [comment]
> I thought one of the reason bittorrent worked was because it seeds even when you are not at your computer... or using the application

BitTorrent works because there are enough people who both (1) have the file you need and (2) are willing to give it to you when you ask.

Seeding from a web browser vs. a desktop app has different characteristics, but they both work in practice. To solve the impermanence of torrents, it's a good idea to add a web seed (http url where the file lives) to the torrent, where possible. Or to add the torrent to a desktop app that supports WebRTC.
