### ISSUE TITLE
Why webtorrent can't release memory after torrent remove?

### ISSUE THREAD

**Issue by catchstar** [webtorrent/webtorrent#1104]
Hey

My code:
```js
const WebTorrent = require('webtorrent');
const client = new WebTorrent();

let magnet = 'magnet:?xt=urn:btih:0EEA3736DD73A5D166BBDF93FF81521E672DF0D1';

const removeTorrent = (magnet) => {
    if(client.get(magnet)){
        client.remove(magnet, ()=>{
            console.log(`remove right`);
        });
    }
};

client.on('torrent', function (torrent) {
    // torrent ready
    // console.log(torrent);

    // remove torrent when torrent ready
    removeTorrent(torrent.magnetURI);
});

client.add(magnet);

// when timeout remove magnet
setTimeout(() => {
    removeTorrent(magnet)
}, 100000);
```

pm2 status:
![1](https://cloud.githubusercontent.com/assets/8263734/25062322/0834a9a8-21fd-11e7-8813-17e4f4a7a756.jpg)
![2](https://cloud.githubusercontent.com/assets/8263734/25062326/0fd2e03a-21fd-11e7-8cab-7b56c31aabdd.jpg)

after the console show torrent remove it still can't release the memory:
![3](https://cloud.githubusercontent.com/assets/8263734/25062328/1806ab88-21fd-11e7-8b54-b38e9c939547.jpg)

After i add some more magnets, my process occur an error because of memory leak.

- WebTorrent version: 0.98.18
- Node.js version: v6.10.2

Please help me check this problem. Thanks a lot.

**Comment by kocoten1992** [comment]
I trace it to https://github.com/feross/buffer

```js
window.x = new Int8Array(256*1024*1024)
window.x = new Int8Array(256*1024*1024)
window.x = new Int8Array(256*1024*1024)
window.x = new Int8Array(256*1024*1024)
```

Run it for a few times, memory never release, it could be from chrome end

**Comment by feross** [comment]
Thanks for the issue. I think you should read a bit about how garbage collection works in JavaScript.

Running `window.x = new Int8Array(256*1024*1024)` will obviously allocate memory that will never be released, since `window.x` is referring to that memory forever.

I can't reproduce your issue. I ran your example code in Node.js and memory utilization went down after remove was called. Please share the version of Node.js or the browser that you're running your code in.
