### ISSUE TITLE
Support iOS 11 (blob redirect issue)

### ISSUE THREAD

**Issue by iShift** [webtorrent/webtorrent#1151]
**What version of WebTorrent?**
Last
**What operating system and Node.js version?**
iOS 11  
**What browser and version? (if using WebTorrent in the browser)**
Safari
**What did you expect to happen?**
Start Streaming
**What actually happened?**
Get error with redirected to blob file.
Same issue on all webtorrents-based sites (instant.io)/

related https://github.com/DiegoRBaquero/BTorrent/issues/48

**Comment by xwjonline** [comment]
I tryed to play video on iPhone 8 Plus which is iOS11, but it started to play video until finished download job.

**Comment by feross** [comment]
Unfortunately, iOS 11 does not support the MediaSource API, which is how we implement streaming in all other browsers.

Safari on macOS got the MediaSource API in version 9, so it seems that Apple has no plans to bring this API to iOS. The solution they recommend on iOS is HLS (HTTP Live Streaming), but this does not work for our use case since we get data over WebRTC (in JS) and HLS only works over HTTP.

It may be possible to hack something together using a ServiceWorker, but this would be very experimental and I'm not interested in attempting it at the moment. Perhaps in the future. If someone builds such a solution, please share it here :)
