### ISSUE TITLE
render-media appendTo callback not fired

### ISSUE THREAD

**Issue by Weedshaker** [webtorrent/webtorrent#1250]
**What version of WebTorrent?**
webtorrent@0.98.20

**What operating system and Node.js version?**
Ubuntu 16.04, Node.js v8.1.3

**What browser and version? (if using WebTorrent in the browser)**
FF 57.0.1, Chrome 63.0.3239.108

**What did you expect to happen?**
appendTo video shall fire a callback when appended

**What actually happened?**
the callback does not get fired when opt is autoplay: false in FireFox and Chrome. Though it works in Chromium. I don't know if the newer version of render-media fixes this issue.

**Comment by feross** [comment]
This bug was likely due to changes in how most browsers handle autoplaying video with audio. Videos that attempt to autoplay with audio are not allowed to play anymore. More details: https://developers.google.com/web/updates/2017/09/autoplay-policy-changes

The `render-media` library has been updated to account for this change. Now the callback is called when the `<video>` tag emits `'canplay'` instead of `'timeupdate'`.

💪
