### ISSUE TITLE
Instructions for noobies

### ISSUE THREAD

**Issue by Luc45** [webtorrent/webtorrent#1277]
Hello!

I'm not very into NPM and I'm trying to use this package...

While following the install instructions presented on README.md, I ran:

```npm install webtorrent```

On a fresh folder. After running this command, I have a folder and a file: node_modules and package.lock.json 

How do I get to the point where I can apply the example usage in the browser as showed in the README.md?

```
var WebTorrent = require('webtorrent')

var client = new WebTorrent()
var magnetURI = '...'

client.add(magnetURI, function (torrent) {
  // Got torrent metadata!
  console.log('Client is downloading:', torrent.infoHash)

  torrent.files.forEach(function (file) {
    // Display the file by appending it to the DOM. Supports video, audio, images, and
    // more. Specify a container element (CSS selector or reference to DOM node).
    file.appendTo('body')
  })
})
```

Edit: I've managed to call `webtorrent.min.js` on a HTML file, but when I try to run the snippet above it says `require() is not defined`.

Edit 2: Allright, moved all content from index.html to a test.js file with the contents above, now when I ran `node test.js` it just died out of memory.

**Comment by Yhozen** [comment]
Node and browser are two different environment. If you want to run that snippet in browser change `var WebTorrent = require('webtorrent')` to `const { WebTorrent } = window` because what webtorrent.min.js is doing is making the webtorrent constructor available in the window object. If you still want to use require you will need to use something like webpack or browserify because require is not available in browser

**Comment by gauravsaini** [comment]
@Luc45 https://nodeschool.io/

**Comment by feross** [comment]
@Yhozen's explanation is correct. Thanks for helping out @Luc45 :)
