### ISSUE TITLE
Seed a torrent file without generating RAM using "Chunks"

### ISSUE THREAD

**Issue by aalhama** [webtorrent/webtorrent#1303]
**What version of WebTorrent?**
webtorrent@0.98.20

**What operating system and Node.js version?**
Linux Mint 18.2, Node.js v6.12.3

**What browser and version? (if using WebTorrent in the browser)**
Google Chrome 64.0.3282

Hello, the problem is that by using Webtorrent in the browser to see a multimedia file of a size such as 500Mb or higher, the RAM memory is filled until either the browser kills the process or the machine bursts. Researching I have seen that you can use the use of "Chunks" to save the content in local and seedear making use of the hard drive. The most interesting methods have been the following:
-idb-chunk-store
-fs-chunk-store
-chunk-store-stream
-ls-chunk-store
![image](https://user-images.githubusercontent.com/22396507/36399630-fbbb72d2-15cc-11e8-9438-3cf436818a6e.png)

I tried the first one (idb-chunk-store) using the parameter that Webtorrent offers that is "store" to indicate the IndexDB and has not been successful since everything correctly storing the data, when it looks, after hashear the torrent the RAM memory keeps filling without stopping. I would like to solve in some way this problem that many people experience. Thank you very much.

**Comment by Weedshaker** [comment]
I was just trying something similar:

https://github.com/webtorrent/webtorrent/issues/1293

though my target is rather to save the torrents plus files for later usage. Eg. when the user revisits, so that they don't have to download the content multiple times.

**Comment by SilentBot1** [comment]
Hey @aalhama, 

After looking through a memory snapshot, the cause of the memory filling up is due to the usage of [immediate-chunk-store](https://www.npmjs.com/package/immediate-chunk-store) in torrent.js[@492](https://github.com/webtorrent/webtorrent/blob/master/lib/torrent.js#L492), which stores the chunk in memory until it is written to the chunk store set in opts.store. In the current implementation of immediate-chunk-store in the webtorrent library, this seems unavoidable if the chosen chunk store is too slow to store the chunks.

This seems to only be an issue when seeding files as read speeds from disk are greater than write speeds to the chunk store. Would reading only chunks of the file at a time be possible instead of processing the whole file at once? 

Hopefully this has been useful, but I would love to hear what peoples thoughts on how to deal with this are.

**Comment by SilentBot1** [comment]
@aalhama @feross,

I have confirmed the issue to be caused by the immediate-chunk-store `store.mem` array filling up with pending writes to a slow stores, such as an IndexedDB store. As the read stream is faster than the store, the pending chunks waiting to be written to store are then stored in `store.mem` until the `store.put` has finished. This eventually builds up on large files (4GB in my case) and causes the browser to crash (tested in both Chrome 64.0.3282.186 and Firefox 58.0.2)

I was able to avoid `store.mem` filling up by using a stream throttle, such as [node-throttle](https://github.com/TooTallNate/node-throttle), in the stream `pump` [here](https://github.com/webtorrent/webtorrent/blob/master/lib/torrent.js#L1616), though setting a universal throttle speed isn't a good solution as user environments may vary, implementing some form of backpressure such as a variable bit rate throttle based on the immediate-chunk-store pending writes would be my two cents but I would love to hear other ideas on how to deal with the situation.

All the best.

**Comment by GooG2e** [comment]
Can you say how I can change store function and does I have some default?
bcause I have tried to set store idb-chunk-store and this doesn't work

**Comment by SilentBot1** [comment]
Hey @GooG2e,

For further questions I would suggest creating a new issue with your question, closing it after creation, instead of tagging onto a different issue. I already included an example which is linked in the thread above but it can be seen directly [here](https://github.com/webtorrent/webtorrent/issues/1293#issuecomment-366587041). As for without using NPM, give this a [look](https://github.com/xuset/indexeddb-chunk-store#install).

If you need any more help, please create a new issue.

**Comment by KayleePop** [comment]
Can you see if this PR helps with this? https://github.com/webtorrent/webtorrent/pull/1456

I created a deployment of instant.io using it here https://spiritual-tenor.glitch.me/ (might take a while to load, be patient)

**Comment by SilentDeath1** [comment]
@KayleePop, this issue still occurs with the changes you have made. 


**Issue:**
Seeding large files, the page crashes due to lack of additional system memory because chosen store is too slow and `immeidate-chunk-store`'s memory buffer fills up all available system memory.


**How to recreate:**
1. Create test file.
OSX - `mkfile -n 8g file.test`
Windows - `fsutil file createnew file.test 8000000000`

2. Drag file into Instant.io instance (https://spiritual-tenor.glitch.me/ or https://instant.io)
3. Wait for metadata to be calculated, as the file is large, this will take a little while.
4. Once metadata has been calculated writing to store will begin.
5. Await for immediate-chunk-store's memory store (`torrent.store.mem`) to consume a large amount of system memory with writes pending to store (`torrent.store.store`)
6. If store isn't fast enough, immediate-chunk-store's memory store will grow too large and cause a page crash.

To view how many chunks are waiting in immediate-chunk-store's memory store the following command can be used once `client.torrents[0].ready === true`:
`client.torrents[0].store.mem.reduce((acc, value)=>{if(value){return acc+1}else{return acc}},0)`
