### ISSUE TITLE
How to get the total content size of a .torrent file or a magnet link?

### ISSUE THREAD

**Issue by Shai1436** [webtorrent/webtorrent#1317]
How to get the total content size of a .torrent file or a magnet link without adding it to a client?
We can add the link to the client, get the total size and remove it from the client. (But it won't delete the file in the temporary folder).
Isn't there a better way to do this? Thanks!

**Comment by SilentBot1** [comment]
Hey @Shai1436,

Your best choice would be to parse the torrent with [parse-torrent] (https://github.com/webtorrent/parse-torrent/)  and then use the .length property though this would only work for a .torrent file. 

Since magnetURI don't contain the metadata, you would have to first find the metadata from a peer before you would know the length, you could use [torrent-discovery](https://github.com/webtorrent/torrent-discovery) though if you use client.add from webtorrent and save the metadata on the metadata event and then destroy the torrent before the ready event, no store should be created. 

Hope this helps!
