### ISSUE TITLE
QUESTION：Is the files being seeded loaded into the memory?

### ISSUE THREAD

**Issue by hz0324** [webtorrent/webtorrent#1343]
I wondered, if I seed a file using webTorrent desktop app. Is the file loaded into memory? Or it just need a file path?
Because I want to seed 1000 files, their size can be really big.

**Comment by KayleePop** [comment]
No, the file is loaded chunk by chunk from the filesystem using [fs-chunk-store](https://github.com/feross/fs-chunk-store)

Here's the relevant bit of code https://github.com/webtorrent/webtorrent/blob/master/lib/torrent.js#L1088

**Comment by feross** [comment]
@hz0324 Even though we don't load the file into memory, it's worth pointing out that seeding 1000 files will likely perform poorly because WebTorrent does not do any kind of resource management. Each torrent instance will just try to use as many resources (connections, CPU, etc.) as it needs. Practically, anything over 10-100 torrents is likely to perform poorly.
