### ISSUE TITLE
Using JWPlayer

### ISSUE THREAD

**Issue by Nou4r** [webtorrent/webtorrent#1377]
I was many people here wanting to use JW Player & VideoJS so i was thinking its possible so why is there no demo code for how it works? So here i am asking the devs seing this post if you could make a simple JW Player & or VideoJS example. Appreciation and donation will be made ofcourse :)

Tyvm

**Comment by feross** [comment]
Hi @Nou4r, I've never used WebTorrent with JW Player or VideoJS. If someone who has done this is willing to send a PR to update the documentation with an example of doing this, I'll happily merge it.

Has anyone used WebTorrent with one of these video player libraries before? cc'ing @webtorrent/folks

**Comment by codealchemist** [comment]
I used VideoJS on [Watchtor](https://open-watchtor.hashbase.io).
https://github.com/codealchemist/watchtor/blob/master/app/scripts/player.js

Maybe we can create a standalone sample if needed.
Cheers!

**Comment by Daniel-Abrecht** [comment]
Here is a JW Player example using my magnet-protocolhandler¹ project:
https://jsfiddle.net/dr2ctgym/5/

The preview image isn't loading yet because it's set as a css background image which my library doesn't yet cover. And auto play doesn't work. But everything else, including the subtitles, should work just fine. I've only tested it in Firefox 52.7.2 ESR and Chromium 64.0.3282.119 at the moment though. In theory, the magnet-protocolhandler should work with any js player & library.

1) https://github.com/Daniel-Abrecht/magnet-protocolhandler
