### ISSUE TITLE
Get Peers without downloading file

### ISSUE THREAD

**Issue by GooG2e** [webtorrent/webtorrent#1397]
Hello!
I have a question - can webtorrent looking for peers without downloading
I think this can speed up init - user opens web page and peer search initialize and when it start playing then we have peers and can instantly use them

**Comment by SilentBot1** [comment]
Hey @GooG2e,

To search for peers, you must know the infoHash of the torrent you are looking for, because of this the torrent must always be added to the client, but you can disable the downloading of the torrent when it's added to the client, connecting to peers but not downloading it.

You could achieve this two ways, firstly manually deselecting the torrent:
```javascript
var sintel = 'magnet:?xt=urn:btih:08ada5a7a6183aae1e09d831df6748d566095a10&dn=Sintel&tr=udp%3A%2F%2Fexplodie.org%3A6969&tr=udp%3A%2F%2Ftracker.coppersurfer.tk%3A6969&tr=udp%3A%2F%2Ftracker.empire-js.us%3A1337&tr=udp%3A%2F%2Ftracker.leechers-paradise.org%3A6969&tr=udp%3A%2F%2Ftracker.opentrackr.org%3A1337&tr=wss%3A%2F%2Ftracker.btorrent.xyz&tr=wss%3A%2F%2Ftracker.fastcast.nz&tr=wss%3A%2F%2Ftracker.openwebtorrent.com&ws=https%3A%2F%2Fwebtorrent.io%2Ftorrents%2F&xs=https%3A%2F%2Fwebtorrent.io%2Ftorrents%2Fsintel.torrent'
var torrent = client.add(sintel)
torrent.on('metadata', t=>{
  // Deselect all pieces so nothing is downloaded.
  t.deselect(0, t.pieces.length - 1, false)
})
```
Secondly this could be achieved with the newly implemented BEP, [BEP 53](http://www.bittorrent.org/beps/bep_0053.html), you could specify the magnetURI parameter `&so` to `&so=` and it would have the same affect as the code example above, though is a new feature so would require installing WebTorrent from GitHub while we wait for a new version to be pushed to npm, because of this I would recommend the first method in the meanwhile.
```javascript
var sintel = 'magnet:?xt=urn:btih:08ada5a7a6183aae1e09d831df6748d566095a10&dn=Sintel&tr=udp%3A%2F%2Fexplodie.org%3A6969&tr=udp%3A%2F%2Ftracker.coppersurfer.tk%3A6969&tr=udp%3A%2F%2Ftracker.empire-js.us%3A1337&tr=udp%3A%2F%2Ftracker.leechers-paradise.org%3A6969&tr=udp%3A%2F%2Ftracker.opentrackr.org%3A1337&tr=wss%3A%2F%2Ftracker.btorrent.xyz&tr=wss%3A%2F%2Ftracker.fastcast.nz&tr=wss%3A%2F%2Ftracker.openwebtorrent.com&ws=https%3A%2F%2Fwebtorrent.io%2Ftorrents%2F&xs=https%3A%2F%2Fwebtorrent.io%2Ftorrents%2Fsintel.torrent'
// Select no files to download
var selectOnly = '&so='
var torrent = client.add(sintel + selectOnly)
```

Both examples given will start downloading the needed pieces when `file.appendTo()` or `file.renderTo()` are called.

All the best :)
