### ISSUE TITLE
Caching problem/Storage Issue

### ISSUE THREAD

**Issue by PenguinInaBand** [webtorrent/webtorrent#1405]
Recently after the new update I've been having consistent issues, where a torrent would download, but wouldn't store. Speeds are consistently above 8MB/s however the actual download remains stuck at around 120~ish MB. I've even seen the download revert back a few times to LESS data being stored. Unsure how to fix this.

**Comment by SilentBot1** [comment]
Hey @PenguinInaBand, 
For us to get a better idea of your issue could you please provide the information below because currently it is unclear as to your issue. Is your issue perhaps for [webtorrent-desktop](https://github.com/webtorrent/webtorrent-desktop)? if so could you please post the issue on that projects issue tracker instead.

**What version of WebTorrent?**
**What operating system and Node.js version?**
**What browser and version? (if using WebTorrent in the browser)**
**What did you expect to happen?**
**What actually happened?**
