### ISSUE TITLE
How to verify if the given torrentId is valid?

### ISSUE THREAD

**Issue by Shai1436** [webtorrent/webtorrent#1416]
Is there any out of the box function to check if the given torrentId/magnetURI is valid before adding it to the client?
Will client.on('error', function (err) {}) API be called in those cases?
If not what is the best way to do it?

**Comment by KayleePop** [comment]
Yep, the error event will be called

https://jsfiddle.net/aw9h86zk/

**Comment by SilentBot1** [comment]
Hey @Shai1436,

As @KayleePop has said, there is no out of the box solution for checking if a identifier is valid before adding it to the client, but the error event will be emitted from the `client` if a identifier isn't valid after being added to the client.

Note: if `torrent.on('error', ()=>{})` is listened to, the error event will be emitted here instead of from the `client`.
