### ISSUE TITLE
WebTorrent not opening in macOS Mojave 10.14

### ISSUE THREAD

**Issue by hellosaumil** [webtorrent/webtorrent#1427]
WebTorrent Version : 0.20.0

OS: macOS Mojave 10.14

It opens with an alert dialog box saying, **The last time you opened WebTorrent, it unexpectedly quit while reopening windows. Do you want to try to reopen its windows again?**
**If you choose not to reopen windows, you may have to open and position the windows yourself.**

Even if I press, **Don't Reopen** or **Reopen Windows**, it _crashes_.

**Comment by SilentBot1** [comment]
Hey @hellosaumil,

I believe this issue is for `webtorrent-desktop` and not the `webtorrent` library itself, because of this I'm going to close this issue. 

Looking at the `webtorrent-desktop` issue tracker, this issue has already been reported and can be seen [here](https://github.com/webtorrent/webtorrent-desktop/), I would check there for further updates.

All the best.
