### ISSUE TITLE
Torrent source. Diference WebTorrent and WebTorrent-Desktop

### ISSUE THREAD

**Issue by heliocaruccio** [webtorrent/webtorrent#1428]
I understand that torrents should be on the WebRTC protocol to work, but why in the case of WebTorrent-Desktop, does any torrent work?

**Comment by SilentBot1** [comment]
Hey @heliocaruccio,

WebTorrent-Desktop is a Electron application which has access to both [Node.JS and Chromium](https://electronjs.org/docs/tutorial/about) within a single runtime, this allows the combination of Chromium's WebRTC abilities and the use of Node.JS's `net` API to create TCP/UDP connections to allow access to both WebRTC peers and TCP/UDP peers within a single application. 

The WebTorrent library works with both TCP/UDP peers and WebRTC peers but within the browser you can't create TCP/UDP connections using JavaScript meaning only WebRTC peers are supported, when using it with Node.JS TCP/UDP peers are supported but WebRTC is only supported in [WebTorrent-Hybrid](https://github.com/webtorrent/webtorrent-hybrid/), but I could never get it to work fully in testing.

I'm going to close this since it's only a question, but feel free to ask any further questions here too!
