### ISSUE TITLE
UDP only

### ISSUE THREAD

**Issue by ohenepee** [webtorrent/webtorrent#1463]
Is there a way to let webtorrent (Node.js) communicate over UDP only (in literally everything)? All clients will definitely be Node.js clients (no Browsers).

**Comment by KayleePop** [comment]
I may be wrong, but I think bittorrent always uses TCP for actually downloading pieces and metadata from peers.

UDP is used for the DHT and for udp trackers though.

I think the reliability of TCP is worth the overhead in this case though, because the order of packets is very important for large files.

Maybe https://www.npmjs.com/package/scuttlebutt would be better for you?

**Comment by ohenepee** [comment]
Thanks... did some research which confirms that YES BitTorrent downloads over TCP... I also found uTP but that sucks beyond the word itself... so many issue around it.
