### ISSUE TITLE
[Feature request] Move (most of) WebTorrent into Web Workers

### ISSUE THREAD

**Issue by jimmywarting** [webtorrent/webtorrent#1524]
Using WebTorrent in the main thread makes the page unresponsive sometimes.
What would it take to move WebTorrent into a web worker?

I know WebRTC is not supported in web workers for example.
So you would have to communicate back and forth with postMessage to handle WebRTC.

----

Almost feel we need a performance sprint and focus on making WebTorrent faster and CPU friendlier.
Having some benchmark testing would be awesome too.

**Comment by jimmywarting** [comment]
Nope, not yet. But it looks like that is just one tiny adjustment (and only for Chrome).
Still think it would be more beneficial to have it all in a web worker

**Comment by Chocobozzz** [comment]
Sure, it was just to know if the patch improved your unresponsive issues. (fyi firefox supports `requestIdleCallback` too)

**Comment by ThaUnknown** [comment]
looking at the current perf comps:
![image](https://github.com/webtorrent/webtorrent/assets/6506529/b95f8257-1a3e-462d-981b-af2c4f59dc46)
I'm trying to think:
- what would we gain from doing this
- what benefits does this offer

most of the CPU time currently sits in the core language features, rather than specific code itself, that is:
#1 function calls
#2 microtask callbacks [from data streams]
#3 idle callbacks [timeouts]

actual code is <8% of the CPU time, so would this actually help with anything?

I guess it could make UI frameworks less choppy in some extreme cases? But without transferable rtcdatachannels which currently no browser supports correctly, all data would need to be postMessage'd from the main thread chunk by chunk, which would introduce significant overhead, and might outweigh the benefits of this?

A good thing would be that we'd gain in-place writes using FSA's SyncAccessHandle, which also performs better, but this again doesn't seem like a major issue, because the chunk store comes it at ~1% of the CPU time, and the in-place stuff I've mostly resolved with chunking and idle saves

I think this isn't worth anymore?
