### ISSUE TITLE
Torrents available to stream in browser

### ISSUE THREAD

**Issue by jaruba** [webtorrent/webtorrent#1531]
I ran across a site that uses webtorrent and seems to keep track of what torrents are available to stream in the browser at all times.

How would one keep track of all the torrents that have the required peers to stream in the browser with webtorrent? I'm guessing it's based on communication with webtorrent specific trackers? If so, there's still the question of how it can be done.

**Comment by jaruba** [comment]
I do realize that only mp4 files would work in the browser, i'm not worried about filtering torrents by mp4 specific files as much as i don't understand how one could request a list of torrents that have web peers and the number of their peers at any given time.

**Comment by SilentBot1** [comment]
Hey @jaruba,

If you run the [tracker](https://github.com/webtorrent/bittorrent-tracker), you can see all infoHashes which use your tracker and how many peers are leeching / seeding the torrent, this alone should be enough information to decide if there is sufficient peers in order to stream the file. 

Writing a simple API around the tracker, which either clients can access or the web server could use to determine which torrents to display, would be the easiest way to achieve this.

As this is a question and not a issue, I'm going to close this but I'm happy to help and continue the conversation.

**Comment by jaruba** [comment]
I could obviously just run my own tracker and hope that people would use it, as if it's not used i wouldn't have any torrents on it to speak of.

I could also interogate webtorrent trackers on a per infohash basis. But this site that i'm talking about, when you go on it, it only shows media that currently has web seeds available and it seems to load this data in 2-3 seconds, on request for the user.

This made me think it literally requests a list of torrents with web seeds from the webtorrent trackers, which afaik shouldn't be possible.

I guess it would also be possible to just filter torrents based on mp4 files, and request data on each from trackers, periodically. I just imagined this website was doing some magical call on the trackers for said data.

**Comment by SilentBot1** [comment]
@jaruba do you have a link to said website (assuming its legal) so I could get a better understanding of it?

By the sounds of it you're saying they're indexing all WebTorrents and displaying those which still have peers seeding which sounds like an impossible task without running their own tracker. Are you sure the website isn't hosting the content themselves rather than indexing public torrents?

**Comment by jaruba** [comment]
I sent you an email (to your public email address shown on your github profile) with the link

**Comment by jaruba** [comment]
> Are you sure the website isn't hosting the content themselves rather than indexing public torrents?

I'm sure their using public torrents and webtorrent, yes.

**Comment by SilentBot1** [comment]
@jaruba after looking at it I can only assume it scrapes torrent indexers, then scrapes the main WebTorrent trackers to check if there are any WebTorrent peers, if so, stores the infohash and periodically checks for peers.
