### ISSUE TITLE
WebTorrent's approach to user identification

### ISSUE THREAD

**Issue by umaar** [webtorrent/webtorrent#1555]
There was an issue raised some time ago where a law firm were asking WebTorrent for assistance in collecting the IP addresses of those who download their customers movies. It appeared the first reply, a WebTorrent contributor, was happy to assist further suggesting the law firm emails them directly.

![image](https://user-images.githubusercontent.com/381495/49286591-8810b900-f492-11e8-820b-55d988d94d91.png)

Could you shed any light on this from a privacy perspective?

- Does WebTorrent assist individuals and organisations who wish to track torrent downloaders/sharers?

**Comment by SilentBot1** [comment]
Hey @umaar,

The only communication I have had with legallaw was in the GitHub issue you're referencing. I haven't had any further contact, outside of publicly in that issue on GitHub, with legallaw or any other law firm regarding WebTorrent.

As WebTorrent is a JavaScript implementation of the BitTorrent protocol, there exists the same privacy concerns in WebTorrent that exist with BitTorrent protocol. Without knowing the infohash or owning the tracker, there is no way to gather information about peers of a torrent. If you know the infohash then it's another story and it's trivial to query trackers for a list of peers, as this is required for the BitTorrent protocol to function. One solution to this is private trackers.

There are three default WSS trackers and, I believe, their respective maintainers are:

wss://tracker.btorrent.xyz - @DiegoRBaquero
wss://tracker.openwebtorrent.com - @alxhotel
wss://tracker.fastcast.nz - @jakefb

The source code for all three trackers are public. 

As a organisation, I haven't seen any other members directly offer to aid somebody in achieving this. Personally I was more interested in discussing the feasibility of implementing this, rather than actually helping implement a solution. I wanted to better understand the possibilities and implications they pose to everybody using the WebTorrent library.

The WebTorrent project and contributors don't condone or support using WebTorrent for copyright infringement, this policy has been stated by Feross since as early as [March 2015](https://github.com/webtorrent/webtorrent/issues/278#issuecomment-78390778).

Because this isn't a issue, I'm going to close mark this as closed, though I'm more than happy to answer any further questions.

**Comment by jimmywarting** [comment]
If you as a peer manage to give out metadata using [Bep 9 - Extension for Peers to Send Metadata Files](http://bittorrent.org/beps/bep_0009.html) or [Bep 28 - Tracker exchange extension](http://bittorrent.org/beps/bep_0028.html) to tell someone to use one of there own wss tracker you will be connected to that and start sharing your upload/download progress

**Comment by umaar** [comment]
Hey @SilentBot1 - really appreciate your detailed response. Your thoughts/statements on WebTorrent is great to hear and is exactly what I was trying to understand more about. 

Thanks for taking the time to explain!
