### ISSUE TITLE
can not download in node.js

### ISSUE THREAD

**Issue by cellargalaxy** [webtorrent/webtorrent#1587]
**What version of WebTorrent?**
webtorrent@0.103.0
**What operating system and Node.js version?**
ubuntu16.04 , node v10.4.1
**What browser and version? (if using WebTorrent in the browser)**
Google Chrome 72.0.3626.119
**What did you expect to happen?**
nodo.js can seed to browser.
**What actually happened?**
In my pc, I seed a file in browser(instant.io) and download torrent from browser. It is success downloading in webtorrent desktop. Browser upload file to webtorrent desktop. But it is fail downloading in  node.js. Node.js always not link to browser or webtorrent desktop. 

bt.js
```js
var WebTorrent = require('webtorrent')

var client = new WebTorrent()

client.add('/home/xxx/xxx.torrent', function (torrent) {
    torrent.on('wire', function (wire, addr) {
        console.log('connected to peer with address ' + addr)
    })
    setInterval(function () {
        console.log('Progress: ' + (torrent.progress * 100).toFixed(1) + '%')
        console.log('numPeers: ' + torrent.numPeers)
        console.log('uploadSpeed: ' + torrent.uploadSpeed)
        console.log('uploadSpeed: ' + torrent.uploadSpeed)
    }, 5000)
})
```
execute `node bt.js`, print:
```
Progress: 0.0%
numPeers: 0
uploadSpeed: 0
uploadSpeed: 0
Progress: 0.0%
numPeers: 0
uploadSpeed: 0
uploadSpeed: 0
......
```

What i do wrong? I am learning javascript. Or can give me some example about this?
thanks

**Comment by Killuah15** [comment]
Hey there, i have the same issue with the latest version. I tested out a few versions of webtorrent to see when was the final version that webtorrent worked with node. For me `webtorrent@0.101.0` is the last version that works, so i guess webtorrent is somehow broken since `webtorrent@0.101.1` I recommend trying a rollback to `webtorrent@0.101.0` and see if that works. :)

### misc for devs
 `client.add(...)` still triggers the callback function which also passes the torrent object, however it seems like it won't get modified / downloaded anymore (Chrome debugger helped me out with this).

**Comment by MeowTheCat** [comment]
I had the same issue. Even I roll back to 0.101.0 as Killuah15 mentioned,  magneturi still doesn't work (.torrent file would work)

**Comment by feross** [comment]
I'm confused by this issue. Are you expecting the `webtorrent` package in node.js to connect with peers in web browsers? This is not possible. You need to use `webtorrent-hybrid` in node.js instead, if you want to connect to browsers.
