### ISSUE TITLE
What is the noPeers event expected behavior?

### ISSUE THREAD

**Issue by KingZee** [webtorrent/webtorrent#1622]
**What version of WebTorrent?**
@latest
**What operating system and Node.js version?**
@latest 

Reproductible snippet : 
```JAVASCRIPT
const wt = require('webtorrent');
var sintel = 'magnet:?xt=urn:btih:08ada5a7a6183aae1e09d831df6748d566095a10&dn=Sintel&tr=udp%3A%2F%2Fexplodie.org%3A6969&tr=udp%3A%2F%2Ftracker.coppersurfer.tk%3A6969&tr=udp%3A%2F%2Ftracker.empire-js.us%3A1337&tr=udp%3A%2F%2Ftracker.leechers-paradise.org%3A6969&tr=udp%3A%2F%2Ftracker.opentrackr.org%3A1337&tr=wss%3A%2F%2Ftracker.btorrent.xyz&tr=wss%3A%2F%2Ftracker.fastcast.nz&tr=wss%3A%2F%2Ftracker.openwebtorrent.com&ws=https%3A%2F%2Fwebtorrent.io%2Ftorrents%2F';
var client = new wt();
var tor = client.add(sintel);
tor.on('noPeers', a => console.log('No '+a+' peers'));
```

Since the 'Sintel' torrent is a very healthy torrent with many active trackers and peers sharing it, I don't understand what would be the use of 'noPeers' if it's called on every announce with no peers. 

Shouldn't the event only be called on edge cases when there are no active peers to continue download of the file, or on a very 'unhealthy' torrent with no peers at all to fetch metadata? This behavior makes the event almost useless in every case, unless I'm understanding it wrong. Thanks!

**Comment by feross** [comment]
I agree that the event doesn't seem very easy to work with. But wouldn't a healthy torrent never have an announce with no peers?

**Comment by KingZee** [comment]
Like I mentioned, the snippet above is a minimal reproductible example. I used the "Sintel" torrent present on the webtorrent.io homepage. The noPeers event is called a few times every time it's added.

**Comment by alxhotel** [comment]
I think one of the reasons this might happen is because at the start of downloading a torrent, when there are no peers, the `update` event of the `bittorrent-racker` is triggered [here](https://github.com/webtorrent/bittorrent-tracker/blob/master/lib/client/websocket-tracker.js#L256), before the event `peer` is emitted [here](https://github.com/webtorrent/bittorrent-tracker/blob/master/lib/client/websocket-tracker.js#L286).

When the `update` event is triggered, it checks for the number of connected peers [here](https://github.com/webtorrent/webtorrent/blob/cd965233cc2b8aa89fce971e9bdefd6a6975b66c/lib/torrent.js#L326), before getting the first peer. Therefore, emitting the `noPeers` event before actually getting the peers.
