### ISSUE TITLE
Possible to get streamable URL?

### ISSUE THREAD

**Issue by Daniele122898** [webtorrent/webtorrent#1628]
Is it possible to get a streamable URL from a torrent. The file.appendTo function can stream the file. But to get the blobUrl the file needs to be fully downloaded first. Is there a way to get a streamable URL that i can hand to a custom player?

I'm writing an react app that has a custom player i use for synchronizing video with other ppl. It just needs a URL to play. Is that possible?

**Comment by jimmywarting** [comment]
What i think you want is actually `file.renderTo(elm)`
(you don't get the blob url, but you get to play it within your own player)

it has to put up some listener like seeking and all of that, so just having a blob url isn't enough

**Comment by feross** [comment]
Exactly what @jimmywarting said. There's not way to just get a URL to pass to your video player since the file has not been downloaded yet. We have to listen for seek events on the player, and prioritize downloaded pieces of the video that the user is trying to watch.

We may be able to solve this with the use of a Service Worker but it is currently not possible.

If you are running in Node.js you can use `createServer()` to get a URL that works even before the video is fully downloaded because then we can respond to the HTTP requests which are made to that server and use that to prioritize which pieces of the video to download.
