### ISSUE TITLE
IPFS support

### ISSUE THREAD

**Issue by monokal** [webtorrent/webtorrent#1642]
I couldn't find any open or closed Issues relating to this, so this is more of a placeholder than anything, however I believe that WebTorrent would be an absolutely game-changing addition to the IPFS network, enabling a new generation of truly decentralised media hosting frontends and social networks. 

Here's a great talk by one of the IPFS guys who achieved the task using HLS: https://www.youtube.com/watch?v=ZYm7cexgSpY

**Comment by feross** [comment]
Hi @monokal, thanks for the issue. The talk you linked to is quite interesting. It's not clear what you mean by WebTorrent being an "addition" to the IPFS network. IPFS and BitTorrent are separate protocols and users need separate clients to interact with the separate networks. If folks are building decentralized apps, it's possible to support files loaded from either network.

I'm closing this issue since there's no bug to fix here, but feel free to continue discussion! ✨
