### ISSUE TITLE
Webseed without .torrent

### ISSUE THREAD

**Issue by pimboli** [webtorrent/webtorrent#1645]
Hello,

Is it possible to stream/download a file only having a magnet link and a webseed?

I have a file called 2.mp4, then I create create a .torrent file with the command:
`create-torrent -urlList 'https://free-cdn.domain.com/2.mp4' 2.mp4 -o 2.torrent `
and with **webtorrent info 2.torrent** I extract the info hash.
The Hash I've got: e78341f222031b8c35076c722e5bbf4877d7f5e2

But unfortunatly I cant access the torrent via this magnet link (with embedded webseed):

`magnet:?xt=urn:btih:e78341f222031b8c35076c722e5bbf4877d7f5e2&dn=2.mp4&tr=udp%3A%2F%2Fexplodie.org%3A6969&tr=udp%3A%2F%2Ftracker.coppersurfer.tk%3A6969&tr=udp%3A%2F%2Ftracker.empire-js.us%3A1337&tr=udp%3A%2F%2Ftracker.leechers-paradise.org%3A6969&tr=udp%3A%2F%2Ftracker.opentrackr.org%3A1337&tr=wss%3A%2F%2Ftracker.btorrent.xyz&tr=wss%3A%2F%2Ftracker.fastcast.nz&tr=wss%3A%2F%2Ftracker.openwebtorrent.com&ws=https%3A%2F%2Ffree-cdn.domain.com%2F2.mp4`

When I create a torrent file with 
`create-torrent -urlList 'https://free-cdn.domain.com/2.mp4' 2.mp4 -o 2.torrent`

and open the torrent file I can download and seed the video, then It works also via the magnet link.

It seems that webtorrent can't handle downloading via magnet if not at least one peer is connected even tough there is a ws defined...

Why??? What am I doing wrong?

Thanks.

**Comment by SilentBot1** [comment]
Hey,

Its not possible to do this.

You require both the magnet and metadata in order to download a torrent
from a WebSeed using a magnet uri.

In a typical scenario with peers who hold the metadata, this option will
work, but if there are no peers with the metadata, this won't work.

Like you've discovered, when using a torrent file, which includes the
needed metadata, this works fine.

If you need any more help with this, please let me know.

**Comment by SilentBot1** [comment]
Hey @pimboli,

I'm going to close the ticket as the question has been answered but if you require further help regarding this issue, please feel free to continue in this ticket and we'll try and help you.

Many thanks,
SilentBot1
