### ISSUE TITLE
Webseed array

### ISSUE THREAD

**Issue by alteoxCOM** [webtorrent/webtorrent#1651]
Hi community,

I found the possibiliy to include a webseed url with the --urlList parameter when creating a torrent file. Is there any possibility to create a torrent file with an array of multiples webseed sources?
Like this we could make the torrent more decentral with multiples webseed urls.

Thank you.

**Comment by SilentBot1** [comment]
Hi @alteoxCOM 

Currently [create-torrent](https://github.com/webtorrent/create-torrent/), which is the module behind the scenes, does actually already support this, just in a unusual way. In order to add multiple webseeds addresses as desired, you must call `--urlList` for each individual address you wish to add to the generated torrent file.

**Example:** `create-torrent .\sintel --urlList https://webtorrent.io/torrents/Sintel/ --urlList https://example.com/torrents/Sintel`

If you have any issues with this or have any more questions, please feel free to re-open the issue.

Kind regards
Brad
