### ISSUE TITLE
XBMC - More Specific

### ISSUE THREAD

**Issue by code-chang** [webtorrent/webtorrent#1652]
XBMC works great, however when you have more than 1 xbmc per network, the current script isn't specific enough.  It just searches all and blasts the stream out.  If someone is using an xbmc elsewhere on the same network their content will get disabled.  Can we have a additional param to specify an IP address?

**Comment by SilentBot1** [comment]
Hi @code-chang 

I believe that this issue is better suited for the [webtorrent-cli](https://github.com/webtorrent/webtorrent-cli) issue tracker.

After looking into the request, it should be simple enough to add a filter with the `--xbmc` argument as it would only involve filtering devices by the `device.config.addresses` property when the `deviceOn` event is being fired in [webtorrent-cli](https://github.com/webtorrent/webtorrent-cli/blob/master/bin/cmd.js#L572).

If you're still interested in getting this implemented, please make another issue over at the [webtorrent-cli](https://github.com/webtorrent/webtorrent-cli) issue tracker and I'll try and get this implemented for you.

Kind regards
Brad
