### ISSUE TITLE
Streaming non-WebRTC torrents?

### ISSUE THREAD

**Issue by htorbov** [webtorrent/webtorrent#1672]
I'm using the following code, and it works perfectly with the sintel.torrent:
```
<!DOCTYPE html>
<html>
<head>
    <title>Torrent Streaming</title>
</head>
<body>
    <div class="result"></div>
    <script src="https://cdn.jsdelivr.net/webtorrent/latest/webtorrent.min.js"></script>
    <script>
        var client = new WebTorrent()

        var torrentId = 'https://webtorrent.io/torrents/sintel.torrent'

        client.add(torrentId, function(torrent) {
            torrent.files.forEach(function(file) {
                file.appendTo(".result");
            })
        })
    </script>
</body>
</html>
```

Then, when I try to change it with some torrent, downloaded from a website, it doesn't stream. The documentation says "keep in mind that the browser can only download torrents that are seeded by WebRTC peers (web peers)". Is there any way to use the script to stream normal torrents, also?

**Comment by SilentBot1** [comment]
Hi @htorbov 

The example `sintel.torrent` will work as there is actively WebRTC peers seeding the content onto the WebRTC swarm for the torrent, other torrents won't have WebRTC peers meaning the torrent's content will be inaccessible in the browser.

From within the browser, there is no way for us to directly speak using the TCP/UDP sockets needed to communicate with regular BitTorrent peers as allowing arbitrary JavaScript access to these communication channels would be a massive security concern.

To 'bridge' the networks, you can either setup a [webtorrent-hybrid](https://github.com/webtorrent/webtorrent-hybrid/) client which seeds between the networks or you can add a webseeds to the torrent in order to provide browser clients an initial seed for the WebRTC swarm.

Alternatively, there have been members of the community who have created custom webseeds which pull content from the BitTorrent network on request and seed it to the WebRTC network as a webseed with the downside of added latency and a single point of failure.

If you have any further questions please feel free to continue the conversation in this thread and the team will respond, but as this isn't a issue, I'm going to close this issue.

Kind regards
Brad

**Comment by adamwoo2444** [comment]
Hi @htorbov  can you tell me how webtorrent-hybrid can stream non-webrtc torrent files? I am using instant.io code and I have changed the require('webtorrent') with require('webtorrent-hybrid') but it is not working. Please guide me how it will stream non-webrtc torrents.

Thank you.
