### ISSUE TITLE
Missing torrent API

### ISSUE THREAD

**Issue by gjuchault** [webtorrent/webtorrent#1705]
**What version of this package are you using?**

N/A

**What operating system, Node.js, and npm version?**

N/A

**What happened?**

Some keys are missing in the torrent documentation (readme):

1. `announce`
2. `maxWebConns`
3. `ready`, `destroyed`, `paused`, `done`
4. `pieces` (and the Piece documentation)
5. `created`, `createdBy`, `comment`
6. `length`, `pieceLength`, `lastPieceLength`

**What did you expect to happen?**

N/A

**Are you willing to submit a pull request to fix this bug?**

Yes

**Comment by feross** [comment]
Hi @gjuchault, thanks for the issue. We'd be happy to accept a PR to add these missing properties to the documentation!

Many of these properties come from the output of [`parse-torrent`](https://github.com/webtorrent/parse-torrent). You can refer to that documentation to make sure you get them all. I would skip the two letter properties that come from magnet links as those are not included if `Torrent` was initialized from a .torrent file instead of a magnet link.

Cheers!

**Comment by gjuchault** [comment]
@feross Which keys are not included in a `.torrent` file ? [It seems](https://github.com/webtorrent/parse-torrent#parse) that `pieceLength` and `lastPieceLength` are included (which makes sense)

**Comment by feross** [comment]
Yep, those two are included.
