### ISSUE TITLE
How to stream torrent while downloading?

### ISSUE THREAD

**Issue by hardx4** [webtorrent/webtorrent#1751]
Hello everyone, first I want to thank you for this great project.

I can download the torrent via client.add, but I still can't understand how to stream it while downloading to the client browser. I saw in the documentation that there is the possibility of using createReadStream, but there is no example of use, could someone give me a hint?

I have only been able to transmit the file after the download completed.

**Comment by KayleePop** [comment]
I made [this demo](https://flems.io/#0=N4IgtglgJlA2CmIBcBWADAOgGwGYA0IAZhAgM7IDaoAdgIZiJIgYBW5BAxgPbUAu8fZCAD0wgAS8AFhFITaAa3izaY0rwBO8emNrUoYgA7qIfWRF5jYJ+GIBGAT0vWxAV1ImA5mO7VSXBBiwXB4AFACUADrUEGAGXOoWalBcLhaE6lxgYgDkkry8BqRIolDwAG6spAZgGBBcwrYZAO6k8OoAtEkpvNlRUT5qqib8sACytB7U8BYAvDlgE1O8SAD8AB68My7q1Ei2vBCSSGgAHLRQtCi0AOy0WACMJzi0tPD38GgAnFBP91CEWGuABYTlAUFgsF8rvc0AAyKDUGYAZWG8FgsI0WygBgApDgAII4gBMADFiST4GsDEEoBB4Bh4h48fisJ9WRj1FjcQTyeSNLQOIp1BhuAYDG1SNtCG0MLx5MzWezMS5sczeaT+YKZfBYhBNO02Bg3Mz7jgcNcOVy1aS+eoBULAvB4BxJBL2gZaHbaa0GeomQTFZ9LSruYSbRq7VrhVxxXxI-Jo36TWaLZiWqRrWSI-aZft4po+Bg1vYAF6W9OZ2054WEWhqDh13gYahltOkDM88MkzUOmMCJrwPPqAtN7hgWEtGZ5AodsNZkkDocj2pcPn5gS8DOk3rUfo8QYcKwbsRzKZNMQAdUHABV13xwn1qAMLLw77NvEfC+coCF3Hw0eMkzTHgYghK+w4bmEJ4AHxiMAURiN4+5pCQNhzOBy7EGQGDEHoIQhFh8BQTMsGEc29BoTMczZCi-6wBgAgYKQCTZJEu7UIhZEcJotD8AASloUBIhoWhgA+HGIWIGAGBA4q-rwySpOEbEAL5sVEGEbgyT7wCE2TJFM2QgeEMFIb4-j0kEoTZJpfBiIQLiwLAjjJE01BBOc8BQKxYQgAQrQIBwBz7kI9z3Eg9yfCAKkALoEFY1DyOQSBUCAdAMEIi62U2kDUJUfkgNssBCNOhTFMIHAIpUpRWGUwpLMI1DVMIWVvgAArAvFKLwLWDtlGC5flBC8PY4pCKQ3Gybw0VxWlFFCFeS7HsJPG5V4AAiOpcNFQA) to demonstrate

You can see that the subtitle file is streamed to the console before the torrent finishes downloading the full torrent because `'torrent fully downloaded'` is logged much later after the entire video file is downloaded.

**Comment by KayleePop** [comment]
closing to keep the issues clean

**Comment by feross** [comment]
Please take a look at the `file.appendTo` method for easy streaming in the browser.

**Comment by PaTiToMaSteR** [comment]
@KayleePop I think that demo must be on the documentation as example of use. Looks really cool and simple!
