### ISSUE TITLE
Possible to write directly to remote storage? (google cloud bucket)?

### ISSUE THREAD

**Issue by RayLuxembourg** [webtorrent/webtorrent#1769]
I have been playing around with createReadStream but i can't seems to make this work.
is it possible?

**Comment by ultimate-tester** [comment]
This does not sound like the responsibility of webtorrent, but the responsibility of the implementer (you). You indeed should createReadStream and pipe the stream into a writestream to Google Cloud Bucket.

It's up to you to find (or write) a library that can create write streams towards Google Cloud Bucket. I did a quick search on NPM to get you started, but found all popular libraries require a filepath instead of a stream. If there are no libraries that accept streams, you should await the download completion and then pass it to the library for Google Cloud Bucket. 

Everything you need to implement this is at your fingertips. Either pipe or wait for `completed` event
