### ISSUE TITLE
webtorrent-desktop on both windows server and Ubuntu vnc server , stop seeding after some time ? what is the problem for that?

### ISSUE THREAD

**Issue by hawkarnote** [webtorrent/webtorrent#1782]
**What version of this package are you using?**

**What operating system, Node.js, and npm version?**

**What happened?**

**What did you expect to happen?**

**Are you willing to submit a pull request to fix this bug?**

**Comment by iagovar** [comment]
Well I have a similar problem. I'm seeding [this video ](https://instant.io/#magnet%3A%3Fxs%3Dhttps%253A%252F%252Fvideo.blender.org%252Fstatic%252Ftorrents%252F3d95fb3d-c866-42c8-9db1-fe82f48ccb95-360.torrent%26xt%3Durn%3Abtih%3A4a5d29d447a4b69c99503d1ac452255b4ad1877c%26dn%3DSpring%2B-%2BBlender%2BOpen%2BMovie%26tr%3Dwss%253A%252F%252Fvideo.blender.org%253A443%252Ftracker%252Fsocket%26tr%3Dhttps%253A%252F%252Fvideo.blender.org%252Ftracker%252Fannounce%26ws%3Dhttps%253A%252F%252Fvideo.blender.org%252Fstatic%252Fwebseed%252F3d95fb3d-c866-42c8-9db1-fe82f48ccb95-360.mp4) from the blender foundation in both a VPS and a home server, both using the webtorrent desktop app v0.21.0

The problem seems to be the tracker, as instant.io seems to print tracking errors from time to time, bot the domain btorrent.xyz always seems up and I didn't find any pattern.
