### ISSUE TITLE
More info

### ISSUE THREAD

**Issue by bystefu** [webtorrent/webtorrent#1797]
Hello, i'm new in webtorrent and javascript.I have some questions,maybe what i ask is already maked,apologize for that.

So, i use webtorrent for browser and i want to know if is any way to pause the downloading of torrent when the progress is more e.g 30%, because i'm not sure if user continue watching to the end.If mp4 video has one hour,maybe in 10 minutes torrent will be complete loaded,and user give up on 15 minutes after.I say that because and 80% from users use data network,and has a GB limit in Europe.

If continue watching, i want to resume the torrent.

Also, i want to know if i can put a limit to speed of upload/download.

**Comment by carlos-menezes** [comment]
You could use `client.on('torrent', function (torrent) {})` ([see](https://github.com/webtorrent/webtorrent/blob/master/docs/api.md#clientontorrent-function-torrent-)), which is emitted when a torrent is ready to be used. Since that returns a `torrent` object, you can check it's progress accessing the `torrent.progress` key ([see](https://github.com/webtorrent/webtorrent/blob/master/docs/api.md#torrentprogress)).
