### ISSUE TITLE
HTML Example not working on my website

### ISSUE THREAD

**Issue by serhatur** [webtorrent/webtorrent#1843]
I copy your example html code to my website but it is not working.it is stuck "Adding magnet".I share the screenshot.

![image](https://user-images.githubusercontent.com/16143728/80816269-e423c380-8bd7-11ea-9d56-fe5a0a6cfac8.png)

**Comment by KayleePop** [comment]
you have to use a websocket tracker (not udp ones which don't work in browser), and there has to be a seeder using that same websocket tracker (DHT doesn't work in browser).

It is waiting to connect to any peers, but it can't find any because you haven't provided any web-compatible sources for peers. (wss tracker)

Try this Sintel torrent, which is well seeded `magnet:?xt=urn:btih:08ada5a7a6183aae1e09d831df6748d566095a10&dn=Sintel&tr=wss%3A%2F%2Ftracker.btorrent.xyz&tr=wss%3A%2F%2Ftracker.fastcast.nz&tr=wss%3A%2F%2Ftracker.openwebtorrent.com`

The websocket tracker parts are these `&tr=wss%3A%2F%2Ftracker.fastcast.nz`
