### ISSUE TITLE
Web seed support for multi-file torrents

### ISSUE THREAD

**Issue by Clodo76** [webtorrent/webtorrent#1844]
**What version of this package are you using?**
Latest .min.js from main website

**What operating system, Node.js, and npm version?**
Browser

**What happened?**
When i use "xs" with a single-file torrent, all works (both .torrent and the file).
But if i use a multi-file torrent, .torrent file works, content files not.

----------
For reference that single-file works

This is a single-file magnet link (in magnet, only infohash and a webseed)
`magnet:?xt=urn:btih:07541fec53c1f2dd28516eb0a99b8e71c182a5f6&xs=https%3A%2F%2Fsearch-id.org%2Fpool%2Ffiles%2F07541fec53c1f2dd28516eb0a99b8e71c182a5f6%2F07541fec53c1f2dd28516eb0a99b8e71c182a5f6.torrent`

Webseed url used for .torrent is correct:
`https://search-id.org/pool/files/07541fec53c1f2dd28516eb0a99b8e71c182a5f6/07541fec53c1f2dd28516eb0a99b8e71c182a5f6.torrent`

Webseed url used for the single file is correct:
`https://search-id.org/pool/files/07541fec53c1f2dd28516eb0a99b8e71c182a5f6/GitHub%20Flavored%20Markdown%20Reference.md`

----------
The issue
(a multi-file torrent that contain an "index.html" and some PNG)

This is a multi-file magnet link:
`magnet:?xt=urn:btih:de3ebc26f74ae97225335bb74083ef67dbe03c00&xs=https%3A%2F%2Fsearch-id.org%2Fpool%2Ffiles%2Fde3ebc26f74ae97225335bb74083ef67dbe03c00%2Fde3ebc26f74ae97225335bb74083ef67dbe03c00.torrent`

Webseed user for .torrent is correct:
`https://search-id.org/pool/files/de3ebc26f74ae97225335bb74083ef67dbe03c00/de3ebc26f74ae97225335bb74083ef67dbe03c00.torrent`

Webseed used for single files NOT.
In Inspector -> Network i see a fetch to
`https://search-id.org/pool/files/de3ebc26f74ae97225335bb74083ef67dbe03c00/0048febbafa8ed9a6f8338a3d43719ff71c010d2.png/archive.is/index.html`

There are the reference of TWO different content files in one url.

I fix this issue with a nginx regex:
`rewrite ^/pool/files/(.+?)/(.+?)/(.+?)/(.+?)$ /pool/files/$1/$3/$4;`
so that trim out the wrong part, and all works perfectly.

So, i think there is a bug, any suggestion to locate this issue in sources to build a pull? Thx

**Comment by KayleePop** [comment]
Try `https://search-id.org/pool/files` instead for the webseed address. I think webtorrent uses the name of the torrent as the folder name and the `ws=` needs to be the parent dir. Not sure, but I think it's intentional behavior?

here's the example magnet link `magnet:?xt=urn:btih:08ada5a7a6183aae1e09d831df6748d566095a10&dn=Sintel&tr=udp%3A%2F%2Fexplodie.org%3A6969&tr=udp%3A%2F%2Ftracker.coppersurfer.tk%3A6969&tr=udp%3A%2F%2Ftracker.empire-js.us%3A1337&tr=udp%3A%2F%2Ftracker.leechers-paradise.org%3A6969&tr=udp%3A%2F%2Ftracker.opentrackr.org%3A1337&tr=wss%3A%2F%2Ftracker.btorrent.xyz&tr=wss%3A%2F%2Ftracker.fastcast.nz&tr=wss%3A%2F%2Ftracker.openwebtorrent.com&ws=https%3A%2F%2Fwebtorrent.io%2Ftorrents%2F&xs=https%3A%2F%2Fwebtorrent.io%2Ftorrents%2Fsintel.torrent`

**Comment by Clodo76** [comment]
Thank you.
So, "xs" must point to webseed .torrent.
"ws" must point to
1- folder, if is a multi-file-torrent, WebTorrent will add the file path for every single file
2- direct path to file, if is a single-file torrent

Not sure about the 2) approach. Why there isn't simply the approach 1) for both type of torrent.
In my system, users can enter directly an infohash alone, i build magnet with webseed, and -maybe- we already webseed that content.
The 2) force me to previously known the files content of a torrent to generate a magnet link with a correct webseed.

**Comment by Clodo76** [comment]
I write a more-specific feature-request here: https://github.com/webtorrent/webtorrent/issues/1848
I'm closing this issue.
