### ISSUE TITLE
torrent name like array

### ISSUE THREAD

**Issue by Hanoosh** [webtorrent/webtorrent#1868]
if a torrent name is like : `example (2019) [1080p] [WEBRip] [5.1] [YTS.MX]`

it will never start download or even get the metadata, i tested this using 3 servers, 2 seeds with different torrent clients.

**Comment by SilentBot1** [comment]
Hi @Hanoosh 

WebTorrent doesn't endorse or assist with piracy in any way and the title posed appears to include piracy, because of this, I'm going to close this issue.

**Note**: WebTorrent can't be used to interface with the existing BitTorrent peer network, only other WebRTC peers, though the WebTorrent-Hybrid library can.

Kind regards
Brad Marsden
