### ISSUE TITLE
WebTorrent should not send unchoke messages to seeders

### ISSUE THREAD

**Issue by alanmcgovern** [webtorrent/webtorrent#1871]
I was playing around with WebTorrent last week to verify a reported bug ( https://github.com/alanmcgovern/monotorrent/issues/300#issuecomment-630380468 ). It looks like the root of that has been resolved ( https://github.com/webtorrent/webtorrent/pull/1870 ), which is great.

I did notice a second bug at the time, but didn't file it. It looks like WebTorrent sends 'Unchoke' messages to peers which have not sent an 'Interested' message. I noticed as the logs for my client indicated it received an `Unchoke` message even though it was a seeder. This should never happen as seeders do not send 'Interested' messages.

Can you double check that you always verify a peer is interested before unchoking it?

**Comment by KayleePop** [comment]
The check happens here https://github.com/webtorrent/webtorrent/blob/master/lib/torrent.js#L1351

isSeeder is set here https://github.com/webtorrent/webtorrent/blob/master/lib/torrent.js#L1044 (on bitfield and have messages as well as initially)

**Comment by alanmcgovern** [comment]
You pointed me at a check for 'isSeeder', but there should be a check for 'isInterested'. Only interested peers should be unchoked.

**Comment by KayleePop** [comment]
hmm. maybe I'm missing something (the code is pretty hard to read), but yeah it looks like uninterested peers are only filtered out for optimistic unchoking and not for bandwidth based unchoking

https://github.com/webtorrent/webtorrent/blob/master/lib/torrent.js#L1373

I'll make a PR, thanks

**Comment by alanmcgovern** [comment]
Sounds great.

I'm not 100% sure which piece of code that refers to, but the piece I was most curious about was this: https://github.com/webtorrent/webtorrent/blob/c9462bd8a789b6599b9ff1cb00b6280597dee519/lib/torrent.js#L1384-L1389 . My reading of this - which could be wrong - is that if a seeder unchokes WebTorrent then WebTorrent will unchoke that seeder, even though the seeder is not interested.

**Comment by alxhotel** [comment]
I think the current implementation is correct based on the specification (https://www.bittorrent.org/beps/bep_0003.html):

> Peers which have a better upload rate but aren't interested get unchoked and if they become interested the worst uploader gets choked

I think this is why the current implementation sends an `unchoke` message to peers not interested. 

In addition, it might happen that a peer becomes a seeder after the client checks the `isSeeder` attribute; thus, the `unchoke` message is still sent because we need to unchoke "the best uploader".

Let me know if my interpretation of the specification is correct.

**Comment by feross** [comment]
@alxhotel I think your interpretation is correct, but it's been a while since I reviewed the spec. It looks like @KayleePop's refactor in https://github.com/webtorrent/webtorrent/pull/1872 did not alter the behavior, so I think we're good as-is.

@alanmcgovern Please let us know if you think this is incorrect and we can look at it again.
