### ISSUE TITLE
client.get is always returning null on http/https url to a torrent file.

### ISSUE THREAD

**Issue by mihaiav** [webtorrent/webtorrent#1875]
**What version of this package are you using?**
0.108.6

**What operating system, Node.js, and npm version?**
browser
**What happened?**
`client.get` is always returning null on http/https url to a torrent file. 
Steps to reproduce:

  - add a torrent using a http/https url to a torrent file (e.g.   client.add("https://webtorrent.io/torrents/sintel.torrent")
  - try to get the torrent by url  (e.g. client.get("https://webtorrent.io/torrents/sintel.torrent"))
 Result: 
   No torrent is returned:

[Here](https://jsfiddle.net/fpchg49k/) is the jsfiddle  link. Below is the code.

```
<!DOCTYPE html>
<html>
  <head>
      <meta charset="UTF-8">
    <script src="https://cdnjs.cloudflare.com/ajax/libs/webtorrent/0.108.6/webtorrent.min.js"></script>
    <script>
      wtc = new WebTorrent();
      const uri = "https://webtorrent.io/torrents/sintel.torrent";
      wtc.add(uri, function(torrent){
        if (wtc.get(uri) === null){
            alert(`BUG: this shouldn't happen! We have torrent ${wtc.torrents[0].infoHash} in list`);
        }
      });
    </script>
  </head>
  <body>
  
  </body>
</html>


```
**What did you expect to happen?**
  I expected  client.get() to return  the torrent object just like it does on magnet links.
**Are you willing to submit a pull request to fix this bug?**
yes

**Comment by mihaiav** [comment]
After more testing it seems the issue is more clear. **`client.get("http://example.com/content.torrent")` always returns undefined even if the torrent already exists** (e.g. you can see with `client.torrents`)

**Comment by ultimate-tester** [comment]
I've had a look, and it seems we cannot fix this without modifying the get function.
Currently the get function simply returns the torrent. We would need to change it to a function with a callback because of the URL. 

An alternative solution which I could think about is to store the URL in the torrent list and looping through the list to get the torrent, preventing the need for a callback. This however wouldn't be smart, because there's no way to guarantee that a URL will always resolve to the exact same torrent. Therefore it should be resolved, and then the hash should be compared.

I'm not sure how to approach this since I'm not involved in this project very much. If anyone could advice on how to deal with breaking changes like these, I can submit my PR (which I have ready to roll, it has a callback instead of return value).

**Comment by mihaiav** [comment]
>  We would need to change it to a function with a callback because of the URL.

If the API is to change I believe we should start using Promises. I actually think methods with callbacks should be refactored into Promises as well. I've searched through the issues and found some discussions about this but apparently nobody pushed through with the new "Promise" API.

https://github.com/webtorrent/webtorrent/issues/1876

> An alternative solution which I could think about is to store the URL in the torrent list and looping through the list to get the torrent, preventing the need for a callback.

That brittle workaround is what I'm using right now...

> If anyone could advice on how to deal with breaking changes like these, I can submit my PR

I'm new to this project as well. However the project seems to be versioned with various releases so I believe breaking changes are acceptable as long as the maintainers agree with the design/changes.
