### ISSUE TITLE
React Native support

### ISSUE THREAD

**Issue by vishalveerareddy** [webtorrent/webtorrent#1917]
There is a urgent requirement in my work.
i want to know how can i use webtorrent in react native android app. Kindly Please help me.

**Comment by feross** [comment]
👋 Thanks for opening an issue. This project is a volunteer-run effort. I don't have any immediate plans to work on this issue, so I'm going to close it.

However, since you mentioned you work for a company... could you consider asking your company to allocate resources toward implementing react-native support and writing some react-native tests and submitting a PR? I'll be happy to review any PR you contribute here.
