### ISSUE TITLE
Custom WebSeed Url for more compatibility

### ISSUE THREAD

**Issue by WatchSoMuch** [webtorrent/webtorrent#1920]
When I have a multifile torrent like example:

http://somesite/Movies/TorrentA/
http://somesite/Movies/TorrentA/File1.mp4
http://somesite/Movies/TorrentA/File2.txt

When I want to add webseed ur to webtorrent, this is how I have to add webseed:
client.addWebSeed("http://somesite/Movies/");

But when I have a single file torrent like example:

http://somesite/Movies/TorrentB/TorrentBFile.mp4

This is the waay I have to set the WebSeed:
client.addWebSeed("http://somesite/Movies/TorrentB/TorrentBFile,mp4");

the problems may occure:
1.This different behavior is a problem by itself. needs more checking the torrent if its multifile or single file when want to add webseed, also needs metadata downloading if we don't have the metadata to check if its multifile or single, metadata download is itself a probem.
2.Most apps using webtorrent are doing the download process automatic using other torrent clients, most torrent apps rename if the torrent folder names are not valid, those torrent will not work on webtorrent,

Example:
http://somesite/Movies/TorrentC:AnInvalidWindowsName/

will be renamed to:

http://somesite/Movies/TorrentC_ValidWindowsName/
http://somesite/Movies/TorrentC_ValidWindowsName/File1.mp4
http://somesite/Movies/TorrentC_ValidWindowsName/File2.txt

So it wont work on webtorrent because webtorrent when needs to play the mp4 file is looking for this address which is not valid:
http://somesite/Movies/TorrentC:AnInvalidWindowsName/File1.mp4

there is no way to make this torrent download by webtorrent because I can not change the path to file in any methods.

suggestions:

I suggest no change on the addWebSeed() method because many existing apps won't work anymore but adding a new method to set the mp4 file, its more like a partial file request while we always want to play the mp4 file in a torrent

client.addWebSeedPartial("http://somesite/Movies/TorrentC_ValidWindowsName/File1.mp4")

**Comment by feross** [comment]
Unfortunately, the inconsistency in the way that you specify web seeds is actually part of the specification itself. See: https://www.bittorrent.org/beps/bep_0019.html However, I agree that we can probably be a bit wiser in how we handle this in the `addWebSeed()` method. We may be able to handle the case where a folder is passed for a single file torrent.

I don't think we'll add a `addWebSeedPartial()` API as that's complicated. Just add the whole folder and `deselect()` the files you're not interested in. Your other issue about Windows file paths is already open here: #1618  In the future, please open a separate issue for each issue instead of putting so many things into one issue.

---

I'll leave this issue open for improving the `addWebSeed()` method to handle the case where a folder is passed for a single file torrent, so the user can use the API the same whether dealing with a single or multi-file torrent.

**Comment by ThaUnknown** [comment]
Moving this conversation to https://github.com/webtorrent/webtorrent/issues/2467 as there are a lot of things wrong with webseeds so this unifies those conversations
