### ISSUE TITLE
webtorrent.io sintel.torrent example isn't working

### ISSUE THREAD

**Issue by therealadityashankar** [webtorrent/webtorrent#1997]
![image](https://user-images.githubusercontent.com/21975892/107079191-80d55a80-6815-11eb-9f20-5aeeaacac61e.png)

tested on Ubuntu 20.10, Firefox 85 and Chromium 88

I usually get like 20 peers but I'm only getting one now so not sure what's going on

also I tested webrtc is working on my browser via a google meet call to myself

**Comment by Iskander0** [comment]
![image](https://user-images.githubusercontent.com/70473827/107673998-2ae23600-6c9f-11eb-8660-01aac79a799f.png)

**Comment by therealadityashankar** [comment]
interesting, can you try the webtorrent.io website, see if the same thing is happening ? (the screenshot does not look like its from the website)

**Comment by paavanb** [comment]
Can confirm, I'm seeing this same behavior. I have [a project experimenting with P2P over webrtc](https://github.com/paavanb/webrtc-experiments) using this library and it worked fantastically (thank you for all your hard work!), but it has since stopped being able to connect to other peers. I suspect something is wrong with wss://tracker.openwebtorrent.com, since the websocket connection to the tracker no longer sends back candidates. I see the same thing on webtorrent.io; I can see my browser hitting the tracker with offers, but this is the only response:
![image](https://user-images.githubusercontent.com/1556995/109437566-6ac15100-79f3-11eb-83d9-af971ddf94b6.png)
After that, the line goes dead with no other traffic.

**Comment by SilentBot1** [comment]
Hi @therealadityashankar,

Are you still having this problem with the current build on [webtorrent.io](webtorrent.io)?

The one peer downloading will likely be the fallback webseed, which is why the content will still load, just slowly.

If you are still experiencing this, are you able to please provide the logs of the session by entering the following into the console and reloading the page `localStorage.debug = '*'`.

If there's any issues with this, just let us know.

Many thanks,
Brad

**Comment by therealadityashankar** [comment]
Yes, I'm still having issues with webtorrent.io, 

the logs are overwhelming to put everything but I suspect most trackers are simply down
![image](https://user-images.githubusercontent.com/21975892/119372924-8035d680-bcd5-11eb-94ca-d5bf45544e77.png)

![image](https://user-images.githubusercontent.com/21975892/119372979-8deb5c00-bcd5-11eb-8d45-ac029045cd10.png)

**Comment by therealadityashankar** [comment]
if you could tell me which logs to exactly put I can help you out more

**Comment by anklimov** [comment]
I have same problem both on my MacBook Pro / chrome (just one peer, movie is plays) and iPhone 12/iOS 14.6/ Firefox, Safari (movie is not playing. )

**Comment by therealadityashankar** [comment]
@feross I am sorry for tagging you but I feel this issue deserves more recognition than it is getting

**Comment by therealadityashankar** [comment]
fixed now, I'm not sure why
