### ISSUE TITLE
能否实现解码流播放

### ISSUE THREAD

**Issue by WZY1999428** [webtorrent/webtorrent#2007]
你好这个程序能否实现解码流播放,我播放一个mkv视频时web页面直接消失了

**Comment by ThaUnknown** [comment]
for future reference: make english issues.
by default webtorrent doesnt support mkv playback since browsers dont really support it because of licensing and all that, it is possible to play mkv videos in chromium based browsers, but those are the only ones that support it, and to do so you'd need some sort of custom implementation

**Comment by WZY1999428** [comment]
打扰下，请问WebTorrent只能使用种子文件进行下载吗，不能使用磁力链接进行下载如此类 链接 magnet:?xt=urn:btih:eeba161a343d4649ef1ed8b7f3a068a34a0523f3&amp;tr 进行下载吗

**Comment by MiTereKun** [comment]
to overcome this limitation - the program suggests using VLC. Can MPV support be added?

**Comment by snowinszu** [comment]
> 打扰下，请问WebTorrent只能使用种子文件进行下载吗，不能使用磁力链接进行下载如此类 链接 magnet:?xt=urn:btih:eeba161a343d4649ef1ed8b7f3a068a34a0523f3&amp;tr 进行下载吗

开源项目功能比较局限，可以考虑用商业化解决方案，比如：https://www.cdnbye.com/cn/

**Comment by WZY1999428** [comment]
thank you




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2021年3月15日(星期一) 晚上10:02
收件人: ***@***.***&gt;; 
抄送: "“ △  ,"<2847656401@QQ.COM&gt;; ***@***.***&gt;; 
主题: Re: [webtorrent/webtorrent] 能否实现解码流播放 (#2007)





  
打扰下，请问WebTorrent只能使用种子文件进行下载吗，不能使用磁力链接进行下载如此类 链接 magnet:?xt=urn:btih:eeba161a343d4649ef1ed8b7f3a068a34a0523f3&amp;tr 进行下载吗
  
开源项目功能比较局限，可以考虑用商业化解决方案，比如：https://www.cdnbye.com/cn/

**Comment by alxhotel** [comment]
Closing this issue, since it seems the question has been answered
