### ISSUE TITLE
why a downloader using 100% CPU?

### ISSUE THREAD

**Issue by darkgirl** [webtorrent/webtorrent#2068]
![捕获1](https://user-images.githubusercontent.com/28688741/118347103-329dc900-b573-11eb-80a5-2a9769377669.PNG)

**Comment by SilentBot1** [comment]
Hi @darkgirl 

This issue appears to be with WebTorrent-Desktop and not the WebTorrent library itself.

Are you able to please re-open this ticket over at the [WebTorrent-Desktop issue tracker](https://github.com/webtorrent/webtorrent-desktop/issues), with the provided template.

Due to this being unrelated, I'm going to close this issue, though if you disagree, please feel free to re-open this.

Many thanks
Brad Marsden
