### ISSUE TITLE
Deprecate render-media (?)

### ISSUE THREAD

**Issue by DiegoRBaquero** [webtorrent/webtorrent#2176]
15% of the minified build is used in render-media

@ThaUnknown

**Comment by ThaUnknown** [comment]
this would be something nice to do in V2, the service worker renderer beats render-media in every aspect except backwards compatibility [which is why I don't want to do it in V1], it works across all browsers [and safari] and has way better codec/container support.

we however can't ditch stream-to-blob-url, because of safari, which ignores service worker url captures when opening new tabs/iframes

its actually not 15% of the minified, build, its 8% [~70kb] of the minified, since a few of its dependencies are re-used in other parts of webtorrent [mainly readable-stream, oopsie!]

I made a PR for this: https://github.com/webtorrent/webtorrent/pull/2180
