### ISSUE TITLE
Webtorrent after version 1.8.8 seems to take a long time to fetch metadata

### ISSUE THREAD

**Issue by canoziia** [webtorrent/webtorrent#2311]
**What version of this package are you using?**

latest(1.8.16) and 1.8.8

**What operating system, Node.js, and npm version?**

Edge 101.0.1210.32 (64 bit)

**What happened?**

Webtorrent v1.8.8 works fine with https://btorrent.xyz but later versions do not. details:

1. seed a files on https://btorrent.xyz and get it's Magnet URI
2. create an html page like [the example](https://github.com/webtorrent/webtorrent/blob/master/docs/get-started.md#complete-html-page-example)
3. now the example is using https://cdn.jsdelivr.net/npm/webtorrent@latest/webtorrent.min.js, and I can't stream the file between the example and btorrent.xyz
4. change the version to webtorrent@1.8.8, successfully streamed the file.

**What did you expect to happen?**

successfully streamed the file with the latest version.

**Are you willing to submit a pull request to fix this bug?**

**Comment by DiegoRBaquero** [comment]
I am thinking mismatch between bugged and fixed version of FAST https://github.com/webtorrent/bittorrent-protocol/commit/a3d28dac8bcf05af5dd12fe82dfbc7abeed4c55a

**Comment by DiegoRBaquero** [comment]
I am updating BTorrent to use latest webtorrent, it was still using 0 range

**Comment by canoziia** [comment]
Thanks. However I think it might be a problem with newer versions of webtorrent. I use the example page to download [Sintel](magnet:?xt=urn:btih:08ada5a7a6183aae1e09d831df6748d566095a10&dn=Sintel&tr=wss%3A%2F%2Ftracker.btorrent.xyz&tr=wss%3A%2F%2Ftracker.openwebtorrent.com&tr=wss%3A%2F%2Ftracker.fastcast.nz), if it is version 1.8.8, it only takes a few seconds to get the metadata, if I use 1.8.16, it takes at least 30s. 

And after btorrent uses version 1.8.16, it becomes difficult to transfer files between two btorrent pages 😂

**Comment by bifeldy** [comment]
Hello, I have the same issue.

My problem is that WebTorrent shows a warning (on warning event, but error message) 'Error: Connection error: Connection failed' (as/at seeder client) on the latest version.

This happens when other people (peer clients) try to connect and download files from the seeder, suddenly that message is shown on the seeder side and the seeder hangs/stop announcing to the tracker site.

So after that warning message, the seeder is now unreachable.

My current workaround is to downgrade back to version 1.5.8 and works fine http://www.hikki.id/torrent (my site).

* I'm using WebTorrent in my Angular 13 project.

**Comment by DiegoRBaquero** [comment]
It is fixed as of 1.8.19 🚀
