### ISSUE TITLE
torrent.destroy()  如何回收内存

### ISSUE THREAD

**Issue by WZY1999428** [webtorrent/webtorrent#2511]
"After I used torrent. destroy() to destroy the download record, the memory was reclaimed. What can I do to reclaim it?".
![image](https://user-images.githubusercontent.com/48763949/227755399-3b3a1866-b95c-42e6-b263-c464f84109e3.png)

**Comment by Leask** [comment]
Same question here. `webtorrent` will eat all the memory after a long time running.

**Comment by ThaUnknown** [comment]
as you said you... destroy the torrent? if you mean in browser, then webtorrent v2 uses FSA API with a fallback to IDB by default, which shouldn't use too much memory. if you mean memory leaks then known ones were fixed in v2 as well, if you mean high base ram usage per torrent you can disable chunk store caching in client.add, limit the amt of peers etc
