### ISSUE TITLE
Already downloaded files are not showing inside torrent.files array

### ISSUE THREAD

**Issue by darkdeathoriginal** [webtorrent/webtorrent#2809]
**What version of this package are you using?**
I am using version 2.4.1

**What operating system, Node.js, and npm version?**
Node : v20.10.0
Npm : 8.19.1
**What happened?**
in the torrent object i got from `client.add(magnet,(torrent)=>{})` there is no reference to already downloaded files. Remaining files are there in torrent.files but already downloaded files are not there.

**What did you expect to happen?**
I want a list of all files not just remaining files.
**Are you willing to submit a pull request to fix this bug?**
I dont know what to do.

**Comment by darkdeathoriginal** [comment]
It was completely my mistake.

**Comment by SilentBot1** [comment]
No worries at all, I'm glad you figured it out.

For clarity, `torrent.files` will be empty when using a magnet until the magnet is resolved via peers on the DHT or trackers and the metadata is retrieved using `ut_metadata` (BEP 9).

You can tell when this happens when the `metadata` event is emitted from the torrent, or when the download is ready to begin (metadata + store is created) when the `ready` event is emitted from the torrent.

The metadata is always parsed in full, with `torrent.files` always containing all files of a torrent, files being already downloaded or not would only affect the `file.done` state.
