### ISSUE TITLE
event when torrent is complete

### ISSUE THREAD

**Issue by webchaz** [webtorrent/webtorrent#383]
I found that there's a `torrent.on('done')` event, but this seems to trigger before the torrent is fully complete.  The progress is at 100, but there's still some more bytes to download for another second or so.  Is there a way to find out when it's completely finished?

**Comment by feross** [comment]
What makes you think that there are still more bytes to download after the `'done'` event is emitted? How are you trying to read the files?

**Comment by webchaz** [comment]
I have the `torrent.swarm.on('download')` event logging and also a `torrent.on('done')` event, the done event logs and then there's still some more logs from the download event.

I also added `client.destroy()` inside the done event and this resulted in a file size that was a bit shy from the expected size.

**Comment by webchaz** [comment]
@feross Here's an example of it: https://gist.github.com/webchaz/ffee62ba9db52c9355ed

You'll see here that it will fire the `done` event, before the `download` event is finished.  If you uncomment the lines 34-36, you'll see that the file size is cut short.

**Comment by feross** [comment]
@webchaz This issue is likely caused by us requesting the same pieces from multiple peers simultaneously. When the final piece arrives from a peer, we emit `'done'` but a few more peers continue to send pieces before we can close the connections. 

Just a guess. Not ideal, I agree. If you send a PR to fix this, I'll happily review it.
