### ISSUE TITLE
DHT module should use the blocklist

### ISSUE THREAD

**Issue by feross** [webtorrent/webtorrent#87]
Currently, the [DHT module](https://github.com/feross/bittorrent-dht) has no notion of blocklists, so it will connect to any IP when doing lookups and announces.

The blocklist feature works correctly for determining whether to connect to a given peer.

**Comment by feross** [comment]
Great news! It turns out that peers discovered via DHT are already being checked against the blocklist. This makes sense because we're calling the same `_addPeer` function that the tracker client calls when it discovers new peers. I added a [test](https://github.com/feross/webtorrent/commit/751702df9564980bb8a2b8cd8334a43c56b010f1) to confirm and preserve this behavior.

To use a blocklist, just specify it on the command line with `--blocklist` or pass the `blocklist` option to the `WebTorrent` constructor.

**Comment by feross** [comment]
So, we'll block bad peers discovered via the DHT, but what if a bad peer is a DHT node? Currently, we still talk to them (add them to the routing table, announce to them, etc.).

This would be easy to fix, but after reading [this huge thread](https://trac.transmissionbt.com/ticket/4016) on the Transmission tracker, and [this research paper](http://www.srhea.net/papers/ntr-worlds05.pdf) on the problems caused by non-transitive connectivity in DHTs, I'm hesitant to use the blocklist on the DHT internals, lest we mess it up for everyone. 

@fisch0920, @jhiesey, @mafintosh: If you have free time and care to dig into this issue (by reading the Transmission thread linked above), I'd value your opinion on this issue. My current thought is to not use the blocklist internally in the DHT. The truly paranoid can always disable the DHT (and I think many tutorials recommend this). But I could be convinced otherwise.

**Comment by Ayms** [comment]
You can take a look at [torrent-live findspies](https://github.com/Ayms/torrent-live#findspies) and [Monitoring and blocking the bittorrent monitoring spies](https://gist.github.com/Ayms/077b114a27450f773939) but the study is undisclosed for now.

Talking about the DHT only, the dangerous spies are not those that you encounter in the DHT, because the messages sent do not prove anything (someone could have spoofed your ip), except maybe when you announce since the token mechanism and the check of your IP is more difficult to fake, this might depend on countries but as far as I know it's not enough to prove anything neither, the proof for the monitors is when you connect to them and start the bittorrent handshake, which is deemed by the spies to be enough while it's not since they usually don't answer correctly.

So, the dangerous spies are those returned as 'values' to get_peers request, they will be blocked by _addPeer

For PEX/client exchange we don't care I think, it's too easy to fake to prove anything.

So I would say that the blocklist is not necessary in the DHT but some might still worry and want it, although it's useless.

Beside blocklists, a good method to protect more privacy, detect, avoid and block the spies is the one described in the findspies link above, this makes the probability to be caught by a dangerous spy quasi null.
