### ISSUE TITLE
Add function to undo appendTo / renderTo

### ISSUE THREAD

**Issue by rafaelleru** [webtorrent/webtorrent#942]
I was looking the API and making my app to stream music, but I can find a option do disappend a file from the body, and the append other I only can play multiple files at the same time. how I can dissapend a file?

**Comment by DiegoRBaquero** [comment]
```js
var el = document.querySelector('#ElementID')
el.parentNode.removeChild(el)
```

That should do :)

**Comment by feross** [comment]
> @DiegoRBaquero That should do :) 

Heh, nice. But I think without an official way to destroy, won't there be errors as `render-media` continues to try to append data to the element. Also, outstanding selections won't get deprioritized.

@rafaelleru What you're asking for is basically the equivalent of `server = torrent.createServer(); server.destroy()`. I think we can just make the `appendTo`/`renderTo` methods return a destroy function that you can call to cleanup everything.

**Comment by qgustavor** [comment]
As those methods internally use render-media, this issue is locked by [render-media#32](https://github.com/feross/render-media/issues/32) which itself can be a little hard to fix as it use many methods to render media. Some modules used, such as videostream and mediasource, export destroy methods. Seems getBlobURL can be destroyed by simply destroying the stream it creates.
